//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLook_Web_APIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguidores
    {
        public string Origem { get; set; }
        public string Destino { get; set; }
        public bool Block { get; set; }
        public System.DateTime C_dataCriacao { get; set; }
        public System.DateTime C_dataAlteracao { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
