//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLook_Web_APIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.convite = new HashSet<convite>();
            this.foto1 = new HashSet<foto>();
            this.interesses = new HashSet<interesses>();
            this.seguidores = new HashSet<seguidores>();
            this.seguidores1 = new HashSet<seguidores>();
        }
    
        public string CloudId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public int Sexo { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Foto { get; set; }
        public string Email { get; set; }
        public string FrasePerfil { get; set; }
        public long Pontos { get; set; }
        public bool Vip { get; set; }
        public System.DateTime C_dataCriacao { get; set; }
        public System.DateTime C_dataAlteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<convite> convite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foto> foto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interesses> interesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguidores> seguidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguidores> seguidores1 { get; set; }
    }
}
